laba2/laba2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

laba2/main/urls.py
from django.urls import path
from main.views import index, words_list, add_word, download_txt

app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
    path('home/', index, name='home'),
    path('words_list/', words_list, name='words_list'),
    path('add_word/', add_word, name='add_word'),
    path('download_txt/', download_txt, name='download_txt')
]

laba2/main/models.py
from django.db import models


class Dictionary(models.Model):
    word = models.CharField(verbose_name='слово', max_length=50)
    translation = models.CharField(verbose_name='перевод', max_length=50)

    class Meta:
        unique_together = (('word', 'translation'),)

laba2/main/forms.py
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS

from main.models import Dictionary


class DictionaryForm(forms.ModelForm):
    class Meta:
        model =Dictionary
        fields = ('word', 'translation')
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "Такая пара уже существует",
            }
        }

laba2/main/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse

from main.models import Dictionary
from main.forms import DictionaryForm


def index(request):
    return render(
        request,
        'index.html'
    )


def words_list(request):
    data = Dictionary.objects.all()
    return render(
        request,
        'words_list.html',
        {
            'dict': data
        }
    )


def add_word(request):
    form = DictionaryForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('main:index')

    return render(
        request,
        'add_word.html',
        {
            'form': form
        }
    )

def download_txt(requests):
    data = ''
    data_pair = Dictionary.objects.all()
    for el in data_pair:
        data += f'{el.word} - {el.translation}\n'

    filename = 'переводы.txt'
    response = HttpResponse(data)
    response['Content-Type'] = 'text/plain; charset=utf-8'
    response['Content-Disposition'] = f'attachment; filename={filename}'
    return response

laba2/templates/add_word.html
{% extends "main.html" %}
{% block content %}
<a href={% url "main:index" %}>
    <button type="submit" class="btn btn-primary">
        Главная
    </button>
</a>
<br>
<br>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
        <label>
        {{ field.label|safe }}
        </label>
        {{ field }}
        <br>
    {% endfor %}
    {{ form.non_field_errors }}
    <button type="submit" class="btn btn-primary">
        Создать перевод
    </button>
</form>
{% endblock content %}

laba2/templates/index.html
{% extends "main.html" %}
{% block content %}

<h1>Это главная</h1>
<a href={% url "main:words_list" %}>
    <button type="submit" class="btn btn-primary">
        Переводы
    </button>
</a>
<a href={% url "main:add_word" %}>
    <button type="submit" class="btn btn-primary">
        Добавить перевод
    </button>
</a>
{% endblock content %}

laba2/templates/main.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="msapplication-TileColor" content="#000" />
    <meta name="theme-color" content="#ffffff" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/css/bootstrap.min.css" integrity="sha512-T584yQ/tdRR5QwOpfvDfVQUidzfgc2339Lc8uBDtcp/wYu80d7jwBgAxbyMh0a9YM9F8N3tdErpFI8iaGx6x5g==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <title>My dictionary</title>
  </head>
  <body>
    <div class="container py-5">
      {% block content %}{% endblock content %}
    </div> 
  </body>
</html>

laba2/templates/words_list.html
{% extends "main.html" %}
{% block content %}
<a href={% url "main:index" %}>
    <button type="submit" class="btn btn-primary">
        Главная
    </button>
</a>
<a href={% url "main:download_txt" %} download="переводы.txt">
    <button type="submit" class="btn btn-primary">
        Скачать словарь
    </button>
</a>
<br>
<br>
<table>
    <tr style="border: 1px solid #000;">
        <td style="border-right: 1px solid black; text-align: center;"><strong>Слово</strong></td>
        <td style="border-right: 1px solid black; text-align: center"><strong>Перевод</strong></td>
    </tr>
    {% for el in dict %}
        <tr style="border: 1px solid #000; text-align: center;">
            <td style="border-right: 1px solid black;"> {{ el.word}} </td>
            <td style="border-right: 1px solid black;"> {{ el.translation }} </td>
        </tr>
    {% endfor %}
</table>

{% endblock content %}